-- TABLE CATEGORY
INSERT INTO `dev-db`.CATEGORY (CATEGORY_ID, NAME) VALUES (1, 'Beschwerde');
INSERT INTO `dev-db`.CATEGORY (CATEGORY_ID, NAME) VALUES (2, 'Anfrage');
INSERT INTO `dev-db`.CATEGORY (CATEGORY_ID, NAME) VALUES (3, 'Sonstiges');

-- TABLE STATUS
INSERT INTO `dev-db`.STATUS (STATUS_ID, NAME) VALUES (1, 'OFFEN');
INSERT INTO `dev-db`.STATUS (STATUS_ID, NAME) VALUES (2, 'IN BEARBEITUNG');
INSERT INTO `dev-db`.STATUS (STATUS_ID, NAME) VALUES (3, 'ABGESCHLOSSEN');


-- TABLE USER
INSERT INTO `dev-db`.USER (EMAIL, NAME, ROLE) VALUES ('test@test.de', 'testuser', 'citizen');
